/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/trailblazer-live.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/trailblazer-live.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="works_prev" position={[5730.657, 286.533, 2.865]}>
          <mesh name="work_prev_01_0" geometry={nodes.work_prev_01_0.geometry} material={materials['material-13']} />
          <mesh name="work_prev_02_1" geometry={nodes.work_prev_02_1.geometry} material={materials['material-12']} position={[859.599, 0, 0]} />
          <mesh name="work_prev_03_2" geometry={nodes.work_prev_03_2.geometry} material={materials['material-11']} position={[1719.197, 0, 0]} />
          <mesh name="work_prev_04_3" geometry={nodes.work_prev_04_3.geometry} material={materials['material-10']} position={[2578.795, 0, 0]} />
          <mesh name="work_prev_05_4" geometry={nodes.work_prev_05_4.geometry} material={materials['material-09']} position={[3438.394, 0, 0]} />
          <mesh name="work_prev_06_5" geometry={nodes.work_prev_06_5.geometry} material={materials['material-08']} position={[4297.993, 0, 0]} />
        </group>
        <group name="works_prev001" position={[5730.657, 286.533, 2.865]}>
          <mesh name="work_prev_01_0001" geometry={nodes.work_prev_01_0001.geometry} material={materials['material-13.001']} />
          <mesh name="work_prev_02_1001" geometry={nodes.work_prev_02_1001.geometry} material={materials['material-12.001']} position={[859.599, 0, 0]} />
          <mesh name="work_prev_03_2001" geometry={nodes.work_prev_03_2001.geometry} material={materials['material-11.001']} position={[1719.197, 0, 0]} />
          <mesh name="work_prev_04_3001" geometry={nodes.work_prev_04_3001.geometry} material={materials['material-10.001']} position={[2578.795, 0, 0]} />
          <mesh name="work_prev_05_4001" geometry={nodes.work_prev_05_4001.geometry} material={materials['material-09.001']} position={[3438.394, 0, 0]} />
          <mesh name="work_prev_06_5001" geometry={nodes.work_prev_06_5001.geometry} material={materials['material-08.001']} position={[4297.993, 0, 0]} />
        </group>
        <mesh name="phone_wow_title_sign" geometry={nodes.phone_wow_title_sign.geometry} material={nodes.phone_wow_title_sign.material} position={[-168.63, 411.866, 0.029]} rotation={[-Math.PI, 0, 0]} />
        <mesh name="phone_descriptor_title_text" geometry={nodes.phone_descriptor_title_text.geometry} material={nodes.phone_descriptor_title_text.material} position={[105.155, 149.455, 0.029]} rotation={[-Math.PI, 0, 0]} />
        <mesh name="phone_arrow_button_main" geometry={nodes.phone_arrow_button_main.geometry} material={nodes.phone_arrow_button_main.material} position={[178.425, 352.847, 0.029]} rotation={[-Math.PI, 0, 0]} />
        <mesh name="contact_button" geometry={nodes.contact_button.geometry} material={nodes.contact_button.material} position={[16572.182, 157.317, 0.029]} />
        <mesh name="about_text_block" geometry={nodes.about_text_block.geometry} material={nodes.about_text_block.material} position={[1715.284, 279.178, 0.029]} />
        <mesh name="crown_sugn_our_service" geometry={nodes.crown_sugn_our_service.geometry} material={nodes.crown_sugn_our_service.material} position={[12035.32, 385.325, 0.029]} />
        <mesh name="hello_sign_contact" geometry={nodes.hello_sign_contact.geometry} material={nodes.hello_sign_contact.material} position={[17046.137, 401.206, 0.029]} />
        <mesh name="omg_sign" geometry={nodes.omg_sign.geometry} material={nodes.omg_sign.material} position={[4320.142, 389.936, 0.029]} />
        <mesh name="Play_button" geometry={nodes.Play_button.geometry} material={nodes.Play_button.material} position={[2864.845, 275.825, -115.224]} />
        <mesh name="portfolio_text_01" geometry={nodes.portfolio_text_01.geometry} material={nodes.portfolio_text_01.material} position={[6151.875, 287.038, 0.029]} />
        <mesh name="portfolio_text_02" geometry={nodes.portfolio_text_02.geometry} material={nodes.portfolio_text_02.material} position={[7004.646, 287.038, 0.029]} />
        <mesh name="portfolio_text_03" geometry={nodes.portfolio_text_03.geometry} material={nodes.portfolio_text_03.material} position={[7858.798, 287.038, 0.029]} />
        <mesh name="portfolio_text_04" geometry={nodes.portfolio_text_04.geometry} material={nodes.portfolio_text_04.material} position={[8730.079, 287.038, 0.029]} />
        <mesh name="portfolio_text_05" geometry={nodes.portfolio_text_05.geometry} material={nodes.portfolio_text_05.material} position={[9580.784, 287.038, 0.029]} />
        <mesh name="portfolio_text_06" geometry={nodes.portfolio_text_06.geometry} material={nodes.portfolio_text_06.material} position={[10447.699, 287.038, 0.029]} />
        <mesh name="screen_showreel" geometry={nodes.screen_showreel.geometry} material={materials['material-04']} position={[2865.328, 286.533, -343.839]} />
        <mesh name="services_text_block" geometry={nodes.services_text_block.geometry} material={nodes.services_text_block.material} position={[14004.598, 252.46, 0.029]} />
        <mesh name="FloorMirror" geometry={nodes.FloorMirror.geometry} material={materials.Tex_02} position={[3133.681, 0.821, 0]} />
        <mesh name="Tex_02_011" geometry={nodes.Tex_02_011.geometry} material={materials.Tex_02} position={[3133.681, 0, 0]} />
        <mesh name="Tex_02_001" geometry={nodes.Tex_02_001.geometry} material={materials.Tex_02} position={[16245.512, 64.865, -444.386]} />
        <mesh name="Tex_02_003" geometry={nodes.Tex_02_003.geometry} material={materials.Tex_02} position={[3133.681, 0, 0]} />
        <mesh name="Tex_02_004" geometry={nodes.Tex_02_004.geometry} material={materials.Tex_02} position={[3133.681, 0, 0]} />
        <mesh name="Tex_02_005" geometry={nodes.Tex_02_005.geometry} material={materials.Tex_02} position={[3133.681, 0, 0]} />
        <mesh name="Tex_02_007" geometry={nodes.Tex_02_007.geometry} material={materials.Tex_02} position={[3133.681, 0, 0]} scale={[1.001, 1, 1]} />
        <mesh name="Tex_02_010" geometry={nodes.Tex_02_010.geometry} material={materials.Tex_02} position={[16045.978, 0, -85.961]} />
        <mesh name="Tex_02_013" geometry={nodes.Tex_02_013.geometry} material={materials.Tex_02} position={[1081.764, 0.233, -483.224]} />
        <mesh name="Tex_02_014" geometry={nodes.Tex_02_014.geometry} material={materials.Tex_02} position={[16045.978, 0, -85.961]} />
        <mesh name="Tex_02_017" geometry={nodes.Tex_02_017.geometry} material={materials.Tex_02} position={[11664.611, 62.413, -470.158]} />
        <mesh name="Tex_02_018" geometry={nodes.Tex_02_018.geometry} material={materials.Tex_02} position={[4642.812, 57.755, -441.286]} scale={[1.067, 1, 1]} />
        <mesh name="Tex_02_019" geometry={nodes.Tex_02_019.geometry} material={materials.Tex_02} position={[1082.438, 21.396, -479.564]} />
        <mesh name="Planet_Rotation" geometry={nodes.Planet_Rotation.geometry} material={materials.Tex_02} position={[16045.839, 286.533, -85.96]} />
        <mesh name="Tex_02_002001" geometry={nodes.Tex_02_002001.geometry} material={materials.Tex_02} position={[2402.938, 33.262, -189.113]} />
        <mesh name="Tex_02_017001" geometry={nodes.Tex_02_017001.geometry} material={materials.Tex_02} position={[11664.611, 62.413, -470.158]} />
        <mesh name="Tex_03" geometry={nodes.Tex_03.geometry} material={materials.Tex_03} scale={821.018} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
        <mesh name="phone_wow_title_sign001" geometry={nodes.phone_wow_title_sign001.geometry} material={nodes.phone_wow_title_sign001.material} position={[-168.63, 411.866, 0.029]} rotation={[-Math.PI, 0, 0]} />
        <mesh name="phone_descriptor_title_text001" geometry={nodes.phone_descriptor_title_text001.geometry} material={nodes.phone_descriptor_title_text001.material} position={[105.155, 149.455, 0.029]} rotation={[-Math.PI, 0, 0]} />
        <mesh name="phone_arrow_button_main001" geometry={nodes.phone_arrow_button_main001.geometry} material={nodes.phone_arrow_button_main001.material} position={[178.425, 352.847, 0.029]} rotation={[-Math.PI, 0, 0]} />
        <mesh name="contact_button001" geometry={nodes.contact_button001.geometry} material={nodes.contact_button001.material} position={[16572.182, 157.317, 0.029]} />
        <mesh name="about_text_block001" geometry={nodes.about_text_block001.geometry} material={nodes.about_text_block001.material} position={[1715.284, 279.178, 0.029]} />
        <mesh name="crown_sugn_our_service001" geometry={nodes.crown_sugn_our_service001.geometry} material={nodes.crown_sugn_our_service001.material} position={[12035.32, 385.325, 0.029]} />
        <mesh name="hello_sign_contact001" geometry={nodes.hello_sign_contact001.geometry} material={nodes.hello_sign_contact001.material} position={[17046.137, 401.206, 0.029]} />
        <mesh name="omg_sign001" geometry={nodes.omg_sign001.geometry} material={nodes.omg_sign001.material} position={[4320.142, 389.936, 0.029]} />
        <mesh name="Play_button001" geometry={nodes.Play_button001.geometry} material={nodes.Play_button001.material} position={[2864.845, 275.825, -115.224]} />
        <mesh name="portfolio_text_01001" geometry={nodes.portfolio_text_01001.geometry} material={nodes.portfolio_text_01001.material} position={[6151.875, 287.038, 0.029]} />
        <mesh name="portfolio_text_02001" geometry={nodes.portfolio_text_02001.geometry} material={nodes.portfolio_text_02001.material} position={[7004.646, 287.038, 0.029]} />
        <mesh name="portfolio_text_03001" geometry={nodes.portfolio_text_03001.geometry} material={nodes.portfolio_text_03001.material} position={[7858.798, 287.038, 0.029]} />
        <mesh name="portfolio_text_04001" geometry={nodes.portfolio_text_04001.geometry} material={nodes.portfolio_text_04001.material} position={[8730.079, 287.038, 0.029]} />
        <mesh name="portfolio_text_05001" geometry={nodes.portfolio_text_05001.geometry} material={nodes.portfolio_text_05001.material} position={[9580.784, 287.038, 0.029]} />
        <mesh name="portfolio_text_06001" geometry={nodes.portfolio_text_06001.geometry} material={nodes.portfolio_text_06001.material} position={[10447.699, 287.038, 0.029]} />
        <mesh name="screen_showreel001" geometry={nodes.screen_showreel001.geometry} material={materials['material-04.001']} position={[2865.328, 286.533, -343.839]} />
        <mesh name="services_text_block001" geometry={nodes.services_text_block001.geometry} material={nodes.services_text_block001.material} position={[14004.598, 252.46, 0.029]} />
        <mesh name="Tex_01002" geometry={nodes.Tex_01002.geometry} material={materials['Tex_01.001']} position={[3133.681, 0, 0]} />
        <mesh name="FloorMirror001" geometry={nodes.FloorMirror001.geometry} material={materials['Tex_02.001']} position={[3133.681, 0.821, 0]} />
        <mesh name="Tex_02_011001" geometry={nodes.Tex_02_011001.geometry} material={materials['Tex_02.001']} position={[3133.681, 0, 0]} />
        <mesh name="Tex_02_001001" geometry={nodes.Tex_02_001001.geometry} material={materials['Tex_02.001']} position={[16245.512, 64.865, -444.386]} />
        <mesh name="Tex_02_003001" geometry={nodes.Tex_02_003001.geometry} material={materials['Tex_02.001']} position={[3133.681, 0, 0]} />
        <mesh name="Tex_02_004001" geometry={nodes.Tex_02_004001.geometry} material={materials['Tex_02.001']} position={[3133.681, 0, 0]} />
        <mesh name="Tex_02_005001" geometry={nodes.Tex_02_005001.geometry} material={materials['Tex_02.001']} position={[3133.681, 0, 0]} />
        <mesh name="Tex_02_007001" geometry={nodes.Tex_02_007001.geometry} material={materials['Tex_02.001']} position={[3133.681, 0, 0]} />
        <mesh name="Tex_02_010001" geometry={nodes.Tex_02_010001.geometry} material={materials['Tex_02.001']} position={[16045.978, 0, -85.961]} />
        <mesh name="Tex_02_013001" geometry={nodes.Tex_02_013001.geometry} material={materials['Tex_02.001']} position={[1081.764, 0.233, -483.224]} />
        <mesh name="Tex_02_014001" geometry={nodes.Tex_02_014001.geometry} material={materials['Tex_02.001']} position={[16045.978, 0, -85.961]} />
        <mesh name="Tex_02_017002" geometry={nodes.Tex_02_017002.geometry} material={materials['Tex_02.001']} position={[11664.611, 62.413, -470.158]} />
        <mesh name="Tex_02_018001" geometry={nodes.Tex_02_018001.geometry} material={materials['Tex_02.001']} position={[4642.812, 57.755, -441.286]} />
        <mesh name="Tex_02_019001" geometry={nodes.Tex_02_019001.geometry} material={materials['Tex_02.001']} position={[1082.438, 21.396, -479.564]} />
        <mesh name="Planet_Rotation001" geometry={nodes.Planet_Rotation001.geometry} material={materials['Tex_02.001']} position={[16045.839, 286.533, -85.96]} />
        <mesh name="Tex_02_002002" geometry={nodes.Tex_02_002002.geometry} material={materials['Tex_02.001']} position={[2402.938, 33.262, -189.113]} />
        <mesh name="Tex_02_017003" geometry={nodes.Tex_02_017003.geometry} material={materials['Tex_02.001']} position={[11664.611, 62.413, -470.158]} />
        <mesh name="Tex_03001" geometry={nodes.Tex_03001.geometry} material={materials['Tex_03.001']} scale={821.018} />
        <mesh name="Text_Var_02" geometry={nodes.Text_Var_02.geometry} material={materials['Tex_03.001']} position={[0.001, 0, 0]} scale={325.173} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[3929.603, 275.143, -108.528]} />
        <mesh name="AirVentF" geometry={nodes.AirVentF.geometry} material={materials.Vent} position={[11484.155, 215.268, 85.09]} rotation={[-Math.PI, -1.173, -Math.PI]} scale={[19.075, 22.384, 38.993]} />
        <mesh name="CoinDoorLock" geometry={nodes.CoinDoorLock.geometry} material={materials.KeyHole} position={[11486.044, 86.806, 92.65]} rotation={[-Math.PI, -1.173, -Math.PI]} scale={[21.023, 24.67, 42.976]} />
        <mesh name="StartButton" geometry={nodes.StartButton.geometry} material={materials.RedButton} position={[11482.251, 150.345, 77.414]} rotation={[-Math.PI, -1.173, 2.845]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="DownButton" geometry={nodes.DownButton.geometry} material={materials.Buttons} position={[11464.271, 143.995, 87.481]} rotation={[-Math.PI, -1.173, 2.845]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="LeftButton" geometry={nodes.LeftButton.geometry} material={materials.Buttons} position={[11456.133, 145.299, 79.888]} rotation={[-Math.PI, -1.173, 2.845]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="UpButton" geometry={nodes.UpButton.geometry} material={materials.Buttons} position={[11462.103, 146.603, 78.834]} rotation={[-Math.PI, -1.173, 2.845]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="GunsButton" geometry={nodes.GunsButton.geometry} material={materials.YellowButton} position={[11468.07, 147.907, 77.778]} rotation={[-Math.PI, -1.173, 2.845]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="CannonButton" geometry={nodes.CannonButton.geometry} material={materials.BlueButton} position={[11476.229, 146.603, 85.383]} rotation={[-Math.PI, -1.173, 2.845]} scale={[3.202, 4.365, 4.215]} />
        <group name="TrackSphere" position={[11509.738, 146.148, 104.173]} rotation={[-Math.PI, -1.173, -Math.PI]} scale={[4.016, 4.712, 8.209]}>
          <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.TrackBall} />
          <mesh name="Sphere_1" geometry={nodes.Sphere_1.geometry} material={materials['Ring(TrackBall)']} />
        </group>
        <mesh name="RightButton" geometry={nodes.RightButton.geometry} material={materials.Buttons} position={[11470.24, 145.299, 86.426]} rotation={[-Math.PI, -1.173, 2.845]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="Slots" geometry={nodes.Slots.geometry} material={materials.CoinSlots} position={[11486.075, 93.433, 92.784]} rotation={[-Math.PI, -1.173, -Math.PI]} scale={[2.297, 2.695, 4.696]} />
        <mesh name="Screws" geometry={nodes.Screws.geometry} material={materials.Screws} position={[11486.044, 86.806, 92.65]} rotation={[-Math.PI, -1.173, -Math.PI]} scale={[21.023, 24.67, 42.976]} />
        <mesh name="CoinDoorFace" geometry={nodes.CoinDoorFace.geometry} material={materials.CoinDoor} position={[11485.802, 85.14, 91.637]} rotation={[-Math.PI, -1.173, -Math.PI]} scale={[21.023, 24.67, 42.976]} />
        <mesh name="Screen" geometry={nodes.Screen.geometry} material={materials['AsterFire Title screen']} position={[11478.871, 179.474, 63.913]} rotation={[1.429, -0.059, 0.394]} scale={[51.134, 28.934, 36.802]} />
        <mesh name="CabinetCenter" geometry={nodes.CabinetCenter.geometry} material={materials.Front} position={[11478.01, 130.915, 60.455]} rotation={[-Math.PI, -1.173, -Math.PI]} scale={[19.075, 22.384, 38.993]} />
        <mesh name="CabinetSides" geometry={nodes.CabinetSides.geometry} material={materials.Sides} position={[11467.024, 171.91, 84.528]} rotation={[-Math.PI, -1.173, -Math.PI]} scale={[25.566, 30.012, 37.487]} />
        <mesh name="AirVentF001" geometry={nodes.AirVentF001.geometry} material={materials.Vent} position={[11326.07, 214.27, 79.813]} rotation={[0, -1.423, 0]} scale={[19.075, 22.384, 38.993]} />
        <mesh name="CoinDoorLock001" geometry={nodes.CoinDoorLock001.geometry} material={materials.KeyHole} position={[11331.607, 85.807, 85.294]} rotation={[0, -1.423, 0]} scale={[21.023, 24.67, 42.976]} />
        <mesh name="StartButton001" geometry={nodes.StartButton001.geometry} material={materials.RedButton} position={[11320.458, 149.346, 74.241]} rotation={[0, -1.423, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="DownButton001" geometry={nodes.DownButton001.geometry} material={materials.Buttons} position={[11310.314, 142.997, 92.178]} rotation={[0, -1.423, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="LeftButton001" geometry={nodes.LeftButton001.geometry} material={materials.Buttons} position={[11299.419, 144.3, 89.913]} rotation={[0, -1.423, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="UpButton001" geometry={nodes.UpButton001.geometry} material={materials.Buttons} position={[11303.973, 145.604, 85.914]} rotation={[0, -1.423, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="GunsButton001" geometry={nodes.GunsButton001.geometry} material={materials.YellowButton} position={[11308.525, 146.908, 81.913]} rotation={[0, -1.423, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="CannonButton001" geometry={nodes.CannonButton001.geometry} material={materials.BlueButton} position={[11319.446, 145.604, 84.178]} rotation={[0, -1.423, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <group name="TrackSphere001" position={[11357.842, 145.149, 82.843]} rotation={[0, -1.423, 0]} scale={[4.016, 4.712, 8.209]}>
          <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials.TrackBall} />
          <mesh name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} material={materials['Ring(TrackBall)']} />
        </group>
        <mesh name="RightButton001" geometry={nodes.RightButton001.geometry} material={materials.Buttons} position={[11314.87, 144.3, 88.178]} rotation={[0, -1.423, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="Slots001" geometry={nodes.Slots001.geometry} material={materials.CoinSlots} position={[11331.704, 92.434, 85.392]} rotation={[0, -1.423, 0]} scale={[2.297, 2.695, 4.696]} />
        <mesh name="Screws001" geometry={nodes.Screws001.geometry} material={materials.Screws} position={[11331.607, 85.807, 85.294]} rotation={[0, -1.423, 0]} scale={[21.023, 24.67, 42.976]} />
        <mesh name="CoinDoorFace001" geometry={nodes.CoinDoorFace001.geometry} material={materials.CoinDoor} position={[11330.875, 84.142, 84.554]} rotation={[0, -1.423, 0]} scale={[21.023, 24.67, 42.976]} />
        <mesh name="Screen001" geometry={nodes.Screen001.geometry} material={materials['AsterFire Title screen']} position={[11310.561, 178.475, 64.456]} rotation={[1.479, 0.019, -0.166]} scale={[51.134, 28.934, 36.802]} />
        <mesh name="CabinetCenter001" geometry={nodes.CabinetCenter001.geometry} material={materials.Front} position={[11308.028, 129.916, 61.947]} rotation={[0, -1.423, 0]} scale={[19.075, 22.384, 38.993]} />
        <mesh name="CabinetSides001" geometry={nodes.CabinetSides001.geometry} material={materials.Sides} position={[11311.136, 170.911, 88.225]} rotation={[0, -1.423, 0]} scale={[25.566, 30.012, 37.487]} />
        <mesh name="AirVentF002" geometry={nodes.AirVentF002.geometry} material={materials.Vent} position={[11173.661, 209.58, 75.576]} rotation={[0, -0.845, 0]} scale={[19.075, 22.384, 38.993]} />
        <mesh name="CoinDoorLock002" geometry={nodes.CoinDoorLock002.geometry} material={materials.KeyHole} position={[11181.295, 81.118, 77.137]} rotation={[0, -0.845, 0]} scale={[21.023, 24.67, 42.976]} />
        <mesh name="StartButton002" geometry={nodes.StartButton002.geometry} material={materials.RedButton} position={[11165.915, 144.657, 73.979]} rotation={[0, -0.845, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="DownButton002" geometry={nodes.DownButton002.geometry} material={materials.Buttons} position={[11167.231, 138.307, 94.543]} rotation={[0, -0.845, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="LeftButton002" geometry={nodes.LeftButton002.geometry} material={materials.Buttons} position={[11156.869, 139.611, 98.605]} rotation={[0, -0.845, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="UpButton002" geometry={nodes.UpButton002.geometry} material={materials.Buttons} position={[11158.496, 140.915, 92.766]} rotation={[0, -0.845, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="GunsButton002" geometry={nodes.GunsButton002.geometry} material={materials.YellowButton} position={[11160.12, 142.219, 86.927]} rotation={[0, -0.845, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="CannonButton002" geometry={nodes.CannonButton002.geometry} material={materials.BlueButton} position={[11170.503, 140.915, 82.852]} rotation={[0, -0.845, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <group name="TrackSphere002" position={[11201.92, 140.46, 60.74]} rotation={[0, -0.845, 0]} scale={[4.016, 4.712, 8.209]}>
          <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials.TrackBall} />
          <mesh name="Sphere002_1" geometry={nodes.Sphere002_1.geometry} material={materials['Ring(TrackBall)']} />
        </group>
        <mesh name="RightButton002" geometry={nodes.RightButton002.geometry} material={materials.Buttons} position={[11168.857, 139.611, 88.703]} rotation={[0, -0.845, -0.297]} scale={[3.202, 4.365, 4.215]} />
        <mesh name="Slots002" geometry={nodes.Slots002.geometry} material={materials.CoinSlots} position={[11181.43, 87.745, 77.166]} rotation={[0, -0.845, 0]} scale={[2.297, 2.695, 4.696]} />
        <mesh name="Screws002" geometry={nodes.Screws002.geometry} material={materials.Screws} position={[11181.295, 81.118, 77.137]} rotation={[0, -0.845, 0]} scale={[21.023, 24.67, 42.976]} />
        <mesh name="CoinDoorFace002" geometry={nodes.CoinDoorFace002.geometry} material={materials.CoinDoor} position={[11180.277, 79.453, 76.918]} rotation={[0, -0.845, 0]} scale={[21.023, 24.67, 42.976]} />
        <mesh name="Screen002" geometry={nodes.Screen002.geometry} material={materials['AsterFire Title screen']} position={[11152.278, 173.786, 71.199]} rotation={[1.455, 0.102, -0.72]} scale={[51.134, 28.934, 36.802]} />
        <mesh name="CabinetCenter002" geometry={nodes.CabinetCenter002.geometry} material={materials.Front} position={[11148.787, 125.227, 70.482]} rotation={[0, -0.845, 0]} scale={[19.075, 22.384, 38.993]} />
        <mesh name="CabinetSides002" geometry={nodes.CabinetSides002.geometry} material={materials.Sides} position={[11165.757, 166.222, 90.785]} rotation={[0, -0.845, 0]} scale={[25.566, 30.012, 37.487]} />
      </group>
    </group>
  )
}

useGLTF.preload('/trailblazer-live.glb')
