/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Office(props) {
  const { nodes, materials } = useGLTF('./models/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0.08, 0, -0.04]} scale={[3, 1, 1]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-3.214, 2.781, -1.678]} scale={[3, 1, 1]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-4.067, 3.661, -4.327]} scale={[10, 1, 1.03]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[2.862, -3.975, -16.991]} />
    </group>
  )
}

useGLTF.preload('./models/model.glb')
